title: owLSM
description: Transform Linux protection with real prevention capabilities
baseurl: "/owLSM"
url: "https://cybereason-labs.github.io"
source: "."

theme: just-the-docs

# Navigation structure
nav_sort: case_insensitive

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 5
  preview_words_before: 10
  preview_words_after: 15
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true


# Color scheme
color_scheme: light

# Aux links (top right) - GitHub and Discord
aux_links:
  "GitHub":
    - "https://github.com/cybereason-labs/owLSM"
  "Discord":
    - "https://discord.gg/gQk5Jxd6vs"
aux_links_new_tab: true

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - scripts
